/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface BatchMinterInterface extends Interface {
    getFunction(nameOrSignature: "MAX_BATCH_SIZE" | "MINT_PRICE" | "arenaWarrior" | "arenaWarriorAddress" | "batchMint" | "onERC721Received"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "BatchMinted"): EventFragment;

    encodeFunctionData(functionFragment: 'MAX_BATCH_SIZE', values?: undefined): string;
encodeFunctionData(functionFragment: 'MINT_PRICE', values?: undefined): string;
encodeFunctionData(functionFragment: 'arenaWarrior', values?: undefined): string;
encodeFunctionData(functionFragment: 'arenaWarriorAddress', values?: undefined): string;
encodeFunctionData(functionFragment: 'batchMint', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'onERC721Received', values: [AddressLike, AddressLike, BigNumberish, BytesLike]): string;

    decodeFunctionResult(functionFragment: 'MAX_BATCH_SIZE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MINT_PRICE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'arenaWarrior', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'arenaWarriorAddress', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'batchMint', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'onERC721Received', data: BytesLike): Result;
  }

  
    export namespace BatchMintedEvent {
      export type InputTuple = [to: AddressLike, quantity: BigNumberish, tokenIds: BigNumberish[]];
      export type OutputTuple = [to: string, quantity: bigint, tokenIds: bigint[]];
      export interface OutputObject {to: string, quantity: bigint, tokenIds: bigint[] };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface BatchMinter extends BaseContract {
    
    connect(runner?: ContractRunner | null): BatchMinter;
    waitForDeployment(): Promise<this>;

    interface: BatchMinterInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    MAX_BATCH_SIZE: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MINT_PRICE: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    arenaWarrior: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    arenaWarriorAddress: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    batchMint: TypedContractMethod<
      [quantity: BigNumberish, ],
      [void],
      'payable'
    >
    

    
    onERC721Received: TypedContractMethod<
      [arg0: AddressLike, arg1: AddressLike, tokenId: BigNumberish, arg3: BytesLike, ],
      [string],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'MAX_BATCH_SIZE'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MINT_PRICE'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'arenaWarrior'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'arenaWarriorAddress'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'batchMint'): TypedContractMethod<
      [quantity: BigNumberish, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'onERC721Received'): TypedContractMethod<
      [arg0: AddressLike, arg1: AddressLike, tokenId: BigNumberish, arg3: BytesLike, ],
      [string],
      'nonpayable'
    >;

    getEvent(key: 'BatchMinted'): TypedContractEvent<BatchMintedEvent.InputTuple, BatchMintedEvent.OutputTuple, BatchMintedEvent.OutputObject>;

    filters: {
      
      'BatchMinted(address,uint256,uint256[])': TypedContractEvent<BatchMintedEvent.InputTuple, BatchMintedEvent.OutputTuple, BatchMintedEvent.OutputObject>;
      BatchMinted: TypedContractEvent<BatchMintedEvent.InputTuple, BatchMintedEvent.OutputTuple, BatchMintedEvent.OutputObject>;
    
    };
  }