/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, BytesLike, AddressLike, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../common.js"
  import type { BattleEngineProxy, BattleEngineProxyInterface } from "../BattleEngineProxy.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "implementation",
        "type": "address"
      },
      {
        "internalType": "bytes",
        "name": "_data",
        "type": "bytes"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "constructor"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "target",
        "type": "address"
      }
    ],
    "name": "AddressEmptyCode",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "implementation",
        "type": "address"
      }
    ],
    "name": "ERC1967InvalidImplementation",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "ERC1967NonPayable",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "ERC1967ProxyUninitialized",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "FailedCall",
    "type": "error"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "implementation",
        "type": "address"
      }
    ],
    "name": "Upgraded",
    "type": "event"
  },
  {
    "stateMutability": "payable",
    "type": "fallback"
  }
] as const;

  const _bytecode = "0x608060405234610164576102b5803803806100198161017c565b9283398101604082820312610164578151916001600160a01b038316908184036101645760208181015190916001600160401b039190828211610164570184601f820112156101645780519182116101685761007d601f8301601f1916840161017c565b94828652838383010111610164575f5b828110610151575050905f918401015281511561013f57823b15610127577f360894a13ba1a3210667c828492db98dca3e2076cc3735a920a3ca505d382bbc80546001600160a01b031916821790557fbc7cd75a20ee27fd9adebab32041f755214dbc6bffa90cc0225b39da2e5c2d3b5f80a280511561012057610110916101a1565b505b604051608290816102338239f35b5050610112565b60249060405190634c9c8ce360e01b82526004820152fd5b6040516330a289cf60e21b8152600490fd5b818101840151868201850152830161008d565b5f80fd5b634e487b7160e01b5f52604160045260245ffd5b6040519190601f01601f191682016001600160401b0381118382101761016857604052565b905f8091602081519101845af4808061021f575b156101d55750506040513d81523d5f602083013e60203d82010160405290565b156101fc57604051639996b31560e01b81526001600160a01b039091166004820152602490fd5b3d1561020d576040513d5f823e3d90fd5b60405163d6bda27560e01b8152600490fd5b503d1515806101b55750813b15156101b556fe60806040527f360894a13ba1a3210667c828492db98dca3e2076cc3735a920a3ca505d382bbc545f9081906001600160a01b0316368280378136915af43d5f803e156048573d5ff35b3d5ffdfea2646970667358221220ad45666e85193ec5c5272b698b394f5af580806f216ec5f11c915a256922377564736f6c63430008180033";

  
      type BattleEngineProxyConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: BattleEngineProxyConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class BattleEngineProxy__factory extends ContractFactory {
    
      constructor(...args: BattleEngineProxyConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(implementation: AddressLike, _data: BytesLike, overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(implementation, _data, overrides || {});
    };
    override deploy(implementation: AddressLike, _data: BytesLike, overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(implementation, _data, overrides || {}) as Promise<BattleEngineProxy & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): BattleEngineProxy__factory {
      return super.connect(runner) as BattleEngineProxy__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): BattleEngineProxyInterface {
      return new Interface(_abi) as BattleEngineProxyInterface;
    }
    
    override attach(address: string | Addressable): BattleEngineProxy {
      return super.attach(address) as BattleEngineProxy;
    }
  static connect(address: string, runner?: ContractRunner | null): BattleEngineProxy {
      return new Contract(address, _abi, runner) as unknown as BattleEngineProxy;
    }
  }

  
  