/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  
export declare namespace GameEngine {
      
    export type GameStruct = {player1: AddressLike, player2: AddressLike, stake: BigNumberish, state: BigNumberish, gameType: BigNumberish, winner: AddressLike, commit1: BytesLike, commit2: BytesLike, move1: BigNumberish, move2: BigNumberish, revealed1: boolean, revealed2: boolean, createdAt: BigNumberish}

    export type GameStructOutput = [player1: string, player2: string, stake: bigint, state: bigint, gameType: bigint, winner: string, commit1: string, commit2: string, move1: bigint, move2: bigint, revealed1: boolean, revealed2: boolean, createdAt: bigint] & {player1: string, player2: string, stake: bigint, state: bigint, gameType: bigint, winner: string, commit1: string, commit2: string, move1: bigint, move2: bigint, revealed1: boolean, revealed2: boolean, createdAt: bigint }
  
    }

  export interface GameEngineInterface extends Interface {
    getFunction(nameOrSignature: "FEE_BASE" | "GAME_TIMEOUT" | "MIN_STAKE" | "PLATFORM_FEE_BPS" | "WIN_POINTS" | "cancelGame" | "claimTimeout" | "commitMove" | "createGame" | "gameCounter" | "getGame" | "joinGame" | "leaderboard" | "owner" | "playerTotalGames" | "playerWins" | "renounceOwnership" | "revealMove" | "rewardVault" | "transferOwnership"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "GameCreated" | "GameFinished" | "GameJoined" | "MoveCommitted" | "MoveRevealed" | "OwnershipTransferred"): EventFragment;

    encodeFunctionData(functionFragment: 'FEE_BASE', values?: undefined): string;
encodeFunctionData(functionFragment: 'GAME_TIMEOUT', values?: undefined): string;
encodeFunctionData(functionFragment: 'MIN_STAKE', values?: undefined): string;
encodeFunctionData(functionFragment: 'PLATFORM_FEE_BPS', values?: undefined): string;
encodeFunctionData(functionFragment: 'WIN_POINTS', values?: undefined): string;
encodeFunctionData(functionFragment: 'cancelGame', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'claimTimeout', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'commitMove', values: [BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'createGame', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'gameCounter', values?: undefined): string;
encodeFunctionData(functionFragment: 'getGame', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'joinGame', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'leaderboard', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'playerTotalGames', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'playerWins', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'revealMove', values: [BigNumberish, BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'rewardVault', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'FEE_BASE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'GAME_TIMEOUT', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MIN_STAKE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'PLATFORM_FEE_BPS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'WIN_POINTS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'cancelGame', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'claimTimeout', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'commitMove', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createGame', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'gameCounter', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getGame', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'joinGame', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'leaderboard', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'playerTotalGames', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'playerWins', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revealMove', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'rewardVault', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
  }

  
    export namespace GameCreatedEvent {
      export type InputTuple = [gameId: BigNumberish, gameType: BigNumberish, player1: AddressLike, stake: BigNumberish];
      export type OutputTuple = [gameId: bigint, gameType: bigint, player1: string, stake: bigint];
      export interface OutputObject {gameId: bigint, gameType: bigint, player1: string, stake: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace GameFinishedEvent {
      export type InputTuple = [gameId: BigNumberish, winner: AddressLike, payout: BigNumberish];
      export type OutputTuple = [gameId: bigint, winner: string, payout: bigint];
      export interface OutputObject {gameId: bigint, winner: string, payout: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace GameJoinedEvent {
      export type InputTuple = [gameId: BigNumberish, player2: AddressLike];
      export type OutputTuple = [gameId: bigint, player2: string];
      export interface OutputObject {gameId: bigint, player2: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MoveCommittedEvent {
      export type InputTuple = [gameId: BigNumberish, player: AddressLike];
      export type OutputTuple = [gameId: bigint, player: string];
      export interface OutputObject {gameId: bigint, player: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MoveRevealedEvent {
      export type InputTuple = [gameId: BigNumberish, player: AddressLike, move: BigNumberish];
      export type OutputTuple = [gameId: bigint, player: string, move: bigint];
      export interface OutputObject {gameId: bigint, player: string, move: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface GameEngine extends BaseContract {
    
    connect(runner?: ContractRunner | null): GameEngine;
    waitForDeployment(): Promise<this>;

    interface: GameEngineInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    FEE_BASE: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    GAME_TIMEOUT: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MIN_STAKE: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    PLATFORM_FEE_BPS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    WIN_POINTS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    cancelGame: TypedContractMethod<
      [_gameId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    claimTimeout: TypedContractMethod<
      [_gameId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    commitMove: TypedContractMethod<
      [_gameId: BigNumberish, _commitHash: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    createGame: TypedContractMethod<
      [_gameType: BigNumberish, ],
      [void],
      'payable'
    >
    

    
    gameCounter: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getGame: TypedContractMethod<
      [_gameId: BigNumberish, ],
      [GameEngine.GameStructOutput],
      'view'
    >
    

    
    joinGame: TypedContractMethod<
      [_gameId: BigNumberish, ],
      [void],
      'payable'
    >
    

    
    leaderboard: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    playerTotalGames: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    playerWins: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    revealMove: TypedContractMethod<
      [_gameId: BigNumberish, _move: BigNumberish, _salt: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    rewardVault: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'FEE_BASE'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'GAME_TIMEOUT'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MIN_STAKE'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'PLATFORM_FEE_BPS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'WIN_POINTS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'cancelGame'): TypedContractMethod<
      [_gameId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'claimTimeout'): TypedContractMethod<
      [_gameId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'commitMove'): TypedContractMethod<
      [_gameId: BigNumberish, _commitHash: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createGame'): TypedContractMethod<
      [_gameType: BigNumberish, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'gameCounter'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getGame'): TypedContractMethod<
      [_gameId: BigNumberish, ],
      [GameEngine.GameStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'joinGame'): TypedContractMethod<
      [_gameId: BigNumberish, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'leaderboard'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'playerTotalGames'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'playerWins'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revealMove'): TypedContractMethod<
      [_gameId: BigNumberish, _move: BigNumberish, _salt: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'rewardVault'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'GameCreated'): TypedContractEvent<GameCreatedEvent.InputTuple, GameCreatedEvent.OutputTuple, GameCreatedEvent.OutputObject>;
getEvent(key: 'GameFinished'): TypedContractEvent<GameFinishedEvent.InputTuple, GameFinishedEvent.OutputTuple, GameFinishedEvent.OutputObject>;
getEvent(key: 'GameJoined'): TypedContractEvent<GameJoinedEvent.InputTuple, GameJoinedEvent.OutputTuple, GameJoinedEvent.OutputObject>;
getEvent(key: 'MoveCommitted'): TypedContractEvent<MoveCommittedEvent.InputTuple, MoveCommittedEvent.OutputTuple, MoveCommittedEvent.OutputObject>;
getEvent(key: 'MoveRevealed'): TypedContractEvent<MoveRevealedEvent.InputTuple, MoveRevealedEvent.OutputTuple, MoveRevealedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;

    filters: {
      
      'GameCreated(uint256,uint8,address,uint256)': TypedContractEvent<GameCreatedEvent.InputTuple, GameCreatedEvent.OutputTuple, GameCreatedEvent.OutputObject>;
      GameCreated: TypedContractEvent<GameCreatedEvent.InputTuple, GameCreatedEvent.OutputTuple, GameCreatedEvent.OutputObject>;
    

      'GameFinished(uint256,address,uint256)': TypedContractEvent<GameFinishedEvent.InputTuple, GameFinishedEvent.OutputTuple, GameFinishedEvent.OutputObject>;
      GameFinished: TypedContractEvent<GameFinishedEvent.InputTuple, GameFinishedEvent.OutputTuple, GameFinishedEvent.OutputObject>;
    

      'GameJoined(uint256,address)': TypedContractEvent<GameJoinedEvent.InputTuple, GameJoinedEvent.OutputTuple, GameJoinedEvent.OutputObject>;
      GameJoined: TypedContractEvent<GameJoinedEvent.InputTuple, GameJoinedEvent.OutputTuple, GameJoinedEvent.OutputObject>;
    

      'MoveCommitted(uint256,address)': TypedContractEvent<MoveCommittedEvent.InputTuple, MoveCommittedEvent.OutputTuple, MoveCommittedEvent.OutputObject>;
      MoveCommitted: TypedContractEvent<MoveCommittedEvent.InputTuple, MoveCommittedEvent.OutputTuple, MoveCommittedEvent.OutputObject>;
    

      'MoveRevealed(uint256,address,uint8)': TypedContractEvent<MoveRevealedEvent.InputTuple, MoveRevealedEvent.OutputTuple, MoveRevealedEvent.OutputObject>;
      MoveRevealed: TypedContractEvent<MoveRevealedEvent.InputTuple, MoveRevealedEvent.OutputTuple, MoveRevealedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    
    };
  }