/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  
export declare namespace FrostbiteIdentityRegistry {
      
    export type AgentStruct = {agentId: BigNumberish, tokenId: BigNumberish, tbaAddress: AddressLike, metadataURI: string, registeredAt: BigNumberish, autoMode: boolean}

    export type AgentStructOutput = [agentId: bigint, tokenId: bigint, tbaAddress: string, metadataURI: string, registeredAt: bigint, autoMode: boolean] & {agentId: bigint, tokenId: bigint, tbaAddress: string, metadataURI: string, registeredAt: bigint, autoMode: boolean }
  
    }

  export interface FrostbiteIdentityRegistryInterface extends Interface {
    getFunction(nameOrSignature: "TBA_SALT" | "arenaWarrior" | "computeTBA" | "deregisterAgent" | "erc6551Registry" | "frostbiteAccountImpl" | "getAgent" | "getAgentByAddress" | "getAutoModeAgentCount" | "getAutoModeAgents" | "isRegistered" | "owner" | "preFusionCleanup" | "registerAgent" | "renounceOwnership" | "setAutoMode" | "tbaChainId" | "totalAgents" | "transferOwnership" | "updateMetadata"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "AgentDeregistered" | "AgentRegistered" | "AutoModeToggled" | "MetadataUpdated" | "OwnershipTransferred"): EventFragment;

    encodeFunctionData(functionFragment: 'TBA_SALT', values?: undefined): string;
encodeFunctionData(functionFragment: 'arenaWarrior', values?: undefined): string;
encodeFunctionData(functionFragment: 'computeTBA', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'deregisterAgent', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'erc6551Registry', values?: undefined): string;
encodeFunctionData(functionFragment: 'frostbiteAccountImpl', values?: undefined): string;
encodeFunctionData(functionFragment: 'getAgent', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getAgentByAddress', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getAutoModeAgentCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'getAutoModeAgents', values?: undefined): string;
encodeFunctionData(functionFragment: 'isRegistered', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'preFusionCleanup', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'registerAgent', values: [BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'setAutoMode', values: [BigNumberish, boolean]): string;
encodeFunctionData(functionFragment: 'tbaChainId', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalAgents', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'updateMetadata', values: [BigNumberish, string]): string;

    decodeFunctionResult(functionFragment: 'TBA_SALT', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'arenaWarrior', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'computeTBA', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'deregisterAgent', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'erc6551Registry', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'frostbiteAccountImpl', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAgent', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAgentByAddress', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAutoModeAgentCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAutoModeAgents', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isRegistered', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'preFusionCleanup', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registerAgent', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setAutoMode', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'tbaChainId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalAgents', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateMetadata', data: BytesLike): Result;
  }

  
    export namespace AgentDeregisteredEvent {
      export type InputTuple = [tokenId: BigNumberish];
      export type OutputTuple = [tokenId: bigint];
      export interface OutputObject {tokenId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace AgentRegisteredEvent {
      export type InputTuple = [agentId: BigNumberish, tokenId: BigNumberish, tbaAddress: AddressLike, metadataURI: string];
      export type OutputTuple = [agentId: bigint, tokenId: bigint, tbaAddress: string, metadataURI: string];
      export interface OutputObject {agentId: bigint, tokenId: bigint, tbaAddress: string, metadataURI: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace AutoModeToggledEvent {
      export type InputTuple = [tokenId: BigNumberish, enabled: boolean];
      export type OutputTuple = [tokenId: bigint, enabled: boolean];
      export interface OutputObject {tokenId: bigint, enabled: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MetadataUpdatedEvent {
      export type InputTuple = [tokenId: BigNumberish, newURI: string];
      export type OutputTuple = [tokenId: bigint, newURI: string];
      export interface OutputObject {tokenId: bigint, newURI: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface FrostbiteIdentityRegistry extends BaseContract {
    
    connect(runner?: ContractRunner | null): FrostbiteIdentityRegistry;
    waitForDeployment(): Promise<this>;

    interface: FrostbiteIdentityRegistryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    TBA_SALT: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    arenaWarrior: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    computeTBA: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [string],
      'view'
    >
    

    
    deregisterAgent: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    erc6551Registry: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    frostbiteAccountImpl: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    getAgent: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [FrostbiteIdentityRegistry.AgentStructOutput],
      'view'
    >
    

    
    getAgentByAddress: TypedContractMethod<
      [tba: AddressLike, ],
      [FrostbiteIdentityRegistry.AgentStructOutput],
      'view'
    >
    

    
    getAutoModeAgentCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getAutoModeAgents: TypedContractMethod<
      [],
      [bigint[]],
      'view'
    >
    

    
    isRegistered: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    preFusionCleanup: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    registerAgent: TypedContractMethod<
      [tokenId: BigNumberish, metadataURI: string, ],
      [void],
      'nonpayable'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    setAutoMode: TypedContractMethod<
      [tokenId: BigNumberish, enabled: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    tbaChainId: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    totalAgents: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    updateMetadata: TypedContractMethod<
      [tokenId: BigNumberish, newURI: string, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'TBA_SALT'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'arenaWarrior'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'computeTBA'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'deregisterAgent'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'erc6551Registry'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'frostbiteAccountImpl'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getAgent'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [FrostbiteIdentityRegistry.AgentStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getAgentByAddress'): TypedContractMethod<
      [tba: AddressLike, ],
      [FrostbiteIdentityRegistry.AgentStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getAutoModeAgentCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getAutoModeAgents'): TypedContractMethod<
      [],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'isRegistered'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'preFusionCleanup'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'registerAgent'): TypedContractMethod<
      [tokenId: BigNumberish, metadataURI: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setAutoMode'): TypedContractMethod<
      [tokenId: BigNumberish, enabled: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'tbaChainId'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'totalAgents'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateMetadata'): TypedContractMethod<
      [tokenId: BigNumberish, newURI: string, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'AgentDeregistered'): TypedContractEvent<AgentDeregisteredEvent.InputTuple, AgentDeregisteredEvent.OutputTuple, AgentDeregisteredEvent.OutputObject>;
getEvent(key: 'AgentRegistered'): TypedContractEvent<AgentRegisteredEvent.InputTuple, AgentRegisteredEvent.OutputTuple, AgentRegisteredEvent.OutputObject>;
getEvent(key: 'AutoModeToggled'): TypedContractEvent<AutoModeToggledEvent.InputTuple, AutoModeToggledEvent.OutputTuple, AutoModeToggledEvent.OutputObject>;
getEvent(key: 'MetadataUpdated'): TypedContractEvent<MetadataUpdatedEvent.InputTuple, MetadataUpdatedEvent.OutputTuple, MetadataUpdatedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;

    filters: {
      
      'AgentDeregistered(uint256)': TypedContractEvent<AgentDeregisteredEvent.InputTuple, AgentDeregisteredEvent.OutputTuple, AgentDeregisteredEvent.OutputObject>;
      AgentDeregistered: TypedContractEvent<AgentDeregisteredEvent.InputTuple, AgentDeregisteredEvent.OutputTuple, AgentDeregisteredEvent.OutputObject>;
    

      'AgentRegistered(uint256,uint256,address,string)': TypedContractEvent<AgentRegisteredEvent.InputTuple, AgentRegisteredEvent.OutputTuple, AgentRegisteredEvent.OutputObject>;
      AgentRegistered: TypedContractEvent<AgentRegisteredEvent.InputTuple, AgentRegisteredEvent.OutputTuple, AgentRegisteredEvent.OutputObject>;
    

      'AutoModeToggled(uint256,bool)': TypedContractEvent<AutoModeToggledEvent.InputTuple, AutoModeToggledEvent.OutputTuple, AutoModeToggledEvent.OutputObject>;
      AutoModeToggled: TypedContractEvent<AutoModeToggledEvent.InputTuple, AutoModeToggledEvent.OutputTuple, AutoModeToggledEvent.OutputObject>;
    

      'MetadataUpdated(uint256,string)': TypedContractEvent<MetadataUpdatedEvent.InputTuple, MetadataUpdatedEvent.OutputTuple, MetadataUpdatedEvent.OutputObject>;
      MetadataUpdated: TypedContractEvent<MetadataUpdatedEvent.InputTuple, MetadataUpdatedEvent.OutputTuple, MetadataUpdatedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    
    };
  }