/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  
export declare namespace FrostbiteAccountV3 {
      
    export type DelegateInfoStruct = {active: boolean, authorizedBy: AddressLike, expiresAt: BigNumberish, budgetTotal: BigNumberish, budgetSpent: BigNumberish}

    export type DelegateInfoStructOutput = [active: boolean, authorizedBy: string, expiresAt: bigint, budgetTotal: bigint, budgetSpent: bigint] & {active: boolean, authorizedBy: string, expiresAt: bigint, budgetTotal: bigint, budgetSpent: bigint }
  
    }

  export interface FrostbiteAccountV3Interface extends Interface {
    getFunction(nameOrSignature: "MAX_LOCK_DURATION" | "addDelegate" | "delegateBudgetRemaining" | "delegateCooldown" | "delegateSpendLimit" | "emergencyFreeze" | "emergencyFrozen" | "emergencyUnfreeze" | "execute" | "getDelegateInfo" | "guardian" | "isAllowedTarget" | "isDelegate" | "isDelegateAllowedSelector" | "isValidSigner" | "lastDelegateExecTime" | "lock" | "lockedUntil" | "owner" | "removeDelegate" | "setAllowedTarget" | "setDelegateAllowedSelector" | "setDelegateBudget" | "setDelegateCooldown" | "setDelegateSpendLimit" | "setGuardian" | "state" | "supportsInterface" | "sweepAVAX" | "token" | "unlock"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "DelegateAdded" | "DelegateBudgetSet" | "DelegateRemoved" | "EmergencyFrozen" | "EmergencyUnfrozen" | "Executed" | "GuardianSet" | "Locked" | "Received" | "Swept" | "Unlocked"): EventFragment;

    encodeFunctionData(functionFragment: 'MAX_LOCK_DURATION', values?: undefined): string;
encodeFunctionData(functionFragment: 'addDelegate', values: [AddressLike, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'delegateBudgetRemaining', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'delegateCooldown', values?: undefined): string;
encodeFunctionData(functionFragment: 'delegateSpendLimit', values?: undefined): string;
encodeFunctionData(functionFragment: 'emergencyFreeze', values?: undefined): string;
encodeFunctionData(functionFragment: 'emergencyFrozen', values?: undefined): string;
encodeFunctionData(functionFragment: 'emergencyUnfreeze', values?: undefined): string;
encodeFunctionData(functionFragment: 'execute', values: [AddressLike, BigNumberish, BytesLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getDelegateInfo', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'guardian', values?: undefined): string;
encodeFunctionData(functionFragment: 'isAllowedTarget', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'isDelegate', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'isDelegateAllowedSelector', values: [AddressLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'isValidSigner', values: [AddressLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'lastDelegateExecTime', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'lock', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'lockedUntil', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'removeDelegate', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setAllowedTarget', values: [AddressLike, boolean]): string;
encodeFunctionData(functionFragment: 'setDelegateAllowedSelector', values: [AddressLike, BytesLike, boolean]): string;
encodeFunctionData(functionFragment: 'setDelegateBudget', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'setDelegateCooldown', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setDelegateSpendLimit', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setGuardian', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'state', values?: undefined): string;
encodeFunctionData(functionFragment: 'supportsInterface', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'sweepAVAX', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'token', values?: undefined): string;
encodeFunctionData(functionFragment: 'unlock', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'MAX_LOCK_DURATION', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'addDelegate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'delegateBudgetRemaining', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'delegateCooldown', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'delegateSpendLimit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'emergencyFreeze', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'emergencyFrozen', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'emergencyUnfreeze', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'execute', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getDelegateInfo', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'guardian', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isAllowedTarget', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isDelegate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isDelegateAllowedSelector', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isValidSigner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'lastDelegateExecTime', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'lock', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'lockedUntil', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'removeDelegate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setAllowedTarget', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setDelegateAllowedSelector', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setDelegateBudget', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setDelegateCooldown', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setDelegateSpendLimit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setGuardian', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'state', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'supportsInterface', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'sweepAVAX', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'token', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unlock', data: BytesLike): Result;
  }

  
    export namespace DelegateAddedEvent {
      export type InputTuple = [delegate: AddressLike, expiresAt: BigNumberish, budget: BigNumberish];
      export type OutputTuple = [delegate: string, expiresAt: bigint, budget: bigint];
      export interface OutputObject {delegate: string, expiresAt: bigint, budget: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DelegateBudgetSetEvent {
      export type InputTuple = [delegate: AddressLike, budget: BigNumberish];
      export type OutputTuple = [delegate: string, budget: bigint];
      export interface OutputObject {delegate: string, budget: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DelegateRemovedEvent {
      export type InputTuple = [delegate: AddressLike];
      export type OutputTuple = [delegate: string];
      export interface OutputObject {delegate: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EmergencyFrozenEvent {
      export type InputTuple = [by: AddressLike];
      export type OutputTuple = [by: string];
      export interface OutputObject {by: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EmergencyUnfrozenEvent {
      export type InputTuple = [];
      export type OutputTuple = [];
      export interface OutputObject {};
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ExecutedEvent {
      export type InputTuple = [to: AddressLike, value: BigNumberish, data: BytesLike, newState: BigNumberish];
      export type OutputTuple = [to: string, value: bigint, data: string, newState: bigint];
      export interface OutputObject {to: string, value: bigint, data: string, newState: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace GuardianSetEvent {
      export type InputTuple = [guardian: AddressLike];
      export type OutputTuple = [guardian: string];
      export interface OutputObject {guardian: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace LockedEvent {
      export type InputTuple = [until: BigNumberish];
      export type OutputTuple = [until: bigint];
      export interface OutputObject {until: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ReceivedEvent {
      export type InputTuple = [from: AddressLike, amount: BigNumberish];
      export type OutputTuple = [from: string, amount: bigint];
      export interface OutputObject {from: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SweptEvent {
      export type InputTuple = [to: AddressLike, amount: BigNumberish];
      export type OutputTuple = [to: string, amount: bigint];
      export interface OutputObject {to: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UnlockedEvent {
      export type InputTuple = [];
      export type OutputTuple = [];
      export interface OutputObject {};
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface FrostbiteAccountV3 extends BaseContract {
    
    connect(runner?: ContractRunner | null): FrostbiteAccountV3;
    waitForDeployment(): Promise<this>;

    interface: FrostbiteAccountV3Interface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    MAX_LOCK_DURATION: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    addDelegate: TypedContractMethod<
      [delegate: AddressLike, expiresAt: BigNumberish, budget: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    delegateBudgetRemaining: TypedContractMethod<
      [delegate: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    delegateCooldown: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    delegateSpendLimit: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    emergencyFreeze: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    emergencyFrozen: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    emergencyUnfreeze: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    execute: TypedContractMethod<
      [to: AddressLike, value: BigNumberish, data: BytesLike, operation: BigNumberish, ],
      [string],
      'payable'
    >
    

    
    getDelegateInfo: TypedContractMethod<
      [addr: AddressLike, ],
      [FrostbiteAccountV3.DelegateInfoStructOutput],
      'view'
    >
    

    
    guardian: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    isAllowedTarget: TypedContractMethod<
      [target: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    isDelegate: TypedContractMethod<
      [addr: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    isDelegateAllowedSelector: TypedContractMethod<
      [target: AddressLike, selector: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    isValidSigner: TypedContractMethod<
      [signer: AddressLike, arg1: BytesLike, ],
      [string],
      'view'
    >
    

    
    lastDelegateExecTime: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    lock: TypedContractMethod<
      [duration: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    lockedUntil: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    removeDelegate: TypedContractMethod<
      [delegate: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setAllowedTarget: TypedContractMethod<
      [target: AddressLike, allowed: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    setDelegateAllowedSelector: TypedContractMethod<
      [target: AddressLike, selector: BytesLike, allowed: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    setDelegateBudget: TypedContractMethod<
      [delegate: AddressLike, budget: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setDelegateCooldown: TypedContractMethod<
      [seconds_: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setDelegateSpendLimit: TypedContractMethod<
      [limit: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setGuardian: TypedContractMethod<
      [_guardian: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    state: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    supportsInterface: TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    sweepAVAX: TypedContractMethod<
      [to: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    token: TypedContractMethod<
      [],
      [[bigint, string, bigint] & {chainId: bigint, tokenContract: string, tokenId: bigint }],
      'view'
    >
    

    
    unlock: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'MAX_LOCK_DURATION'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'addDelegate'): TypedContractMethod<
      [delegate: AddressLike, expiresAt: BigNumberish, budget: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'delegateBudgetRemaining'): TypedContractMethod<
      [delegate: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'delegateCooldown'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'delegateSpendLimit'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'emergencyFreeze'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'emergencyFrozen'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'emergencyUnfreeze'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'execute'): TypedContractMethod<
      [to: AddressLike, value: BigNumberish, data: BytesLike, operation: BigNumberish, ],
      [string],
      'payable'
    >;
getFunction(nameOrSignature: 'getDelegateInfo'): TypedContractMethod<
      [addr: AddressLike, ],
      [FrostbiteAccountV3.DelegateInfoStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'guardian'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'isAllowedTarget'): TypedContractMethod<
      [target: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isDelegate'): TypedContractMethod<
      [addr: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isDelegateAllowedSelector'): TypedContractMethod<
      [target: AddressLike, selector: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isValidSigner'): TypedContractMethod<
      [signer: AddressLike, arg1: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'lastDelegateExecTime'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'lock'): TypedContractMethod<
      [duration: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'lockedUntil'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'removeDelegate'): TypedContractMethod<
      [delegate: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setAllowedTarget'): TypedContractMethod<
      [target: AddressLike, allowed: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setDelegateAllowedSelector'): TypedContractMethod<
      [target: AddressLike, selector: BytesLike, allowed: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setDelegateBudget'): TypedContractMethod<
      [delegate: AddressLike, budget: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setDelegateCooldown'): TypedContractMethod<
      [seconds_: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setDelegateSpendLimit'): TypedContractMethod<
      [limit: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setGuardian'): TypedContractMethod<
      [_guardian: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'state'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'supportsInterface'): TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'sweepAVAX'): TypedContractMethod<
      [to: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'token'): TypedContractMethod<
      [],
      [[bigint, string, bigint] & {chainId: bigint, tokenContract: string, tokenId: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'unlock'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'DelegateAdded'): TypedContractEvent<DelegateAddedEvent.InputTuple, DelegateAddedEvent.OutputTuple, DelegateAddedEvent.OutputObject>;
getEvent(key: 'DelegateBudgetSet'): TypedContractEvent<DelegateBudgetSetEvent.InputTuple, DelegateBudgetSetEvent.OutputTuple, DelegateBudgetSetEvent.OutputObject>;
getEvent(key: 'DelegateRemoved'): TypedContractEvent<DelegateRemovedEvent.InputTuple, DelegateRemovedEvent.OutputTuple, DelegateRemovedEvent.OutputObject>;
getEvent(key: 'EmergencyFrozen'): TypedContractEvent<EmergencyFrozenEvent.InputTuple, EmergencyFrozenEvent.OutputTuple, EmergencyFrozenEvent.OutputObject>;
getEvent(key: 'EmergencyUnfrozen'): TypedContractEvent<EmergencyUnfrozenEvent.InputTuple, EmergencyUnfrozenEvent.OutputTuple, EmergencyUnfrozenEvent.OutputObject>;
getEvent(key: 'Executed'): TypedContractEvent<ExecutedEvent.InputTuple, ExecutedEvent.OutputTuple, ExecutedEvent.OutputObject>;
getEvent(key: 'GuardianSet'): TypedContractEvent<GuardianSetEvent.InputTuple, GuardianSetEvent.OutputTuple, GuardianSetEvent.OutputObject>;
getEvent(key: 'Locked'): TypedContractEvent<LockedEvent.InputTuple, LockedEvent.OutputTuple, LockedEvent.OutputObject>;
getEvent(key: 'Received'): TypedContractEvent<ReceivedEvent.InputTuple, ReceivedEvent.OutputTuple, ReceivedEvent.OutputObject>;
getEvent(key: 'Swept'): TypedContractEvent<SweptEvent.InputTuple, SweptEvent.OutputTuple, SweptEvent.OutputObject>;
getEvent(key: 'Unlocked'): TypedContractEvent<UnlockedEvent.InputTuple, UnlockedEvent.OutputTuple, UnlockedEvent.OutputObject>;

    filters: {
      
      'DelegateAdded(address,uint256,uint256)': TypedContractEvent<DelegateAddedEvent.InputTuple, DelegateAddedEvent.OutputTuple, DelegateAddedEvent.OutputObject>;
      DelegateAdded: TypedContractEvent<DelegateAddedEvent.InputTuple, DelegateAddedEvent.OutputTuple, DelegateAddedEvent.OutputObject>;
    

      'DelegateBudgetSet(address,uint256)': TypedContractEvent<DelegateBudgetSetEvent.InputTuple, DelegateBudgetSetEvent.OutputTuple, DelegateBudgetSetEvent.OutputObject>;
      DelegateBudgetSet: TypedContractEvent<DelegateBudgetSetEvent.InputTuple, DelegateBudgetSetEvent.OutputTuple, DelegateBudgetSetEvent.OutputObject>;
    

      'DelegateRemoved(address)': TypedContractEvent<DelegateRemovedEvent.InputTuple, DelegateRemovedEvent.OutputTuple, DelegateRemovedEvent.OutputObject>;
      DelegateRemoved: TypedContractEvent<DelegateRemovedEvent.InputTuple, DelegateRemovedEvent.OutputTuple, DelegateRemovedEvent.OutputObject>;
    

      'EmergencyFrozen(address)': TypedContractEvent<EmergencyFrozenEvent.InputTuple, EmergencyFrozenEvent.OutputTuple, EmergencyFrozenEvent.OutputObject>;
      EmergencyFrozen: TypedContractEvent<EmergencyFrozenEvent.InputTuple, EmergencyFrozenEvent.OutputTuple, EmergencyFrozenEvent.OutputObject>;
    

      'EmergencyUnfrozen()': TypedContractEvent<EmergencyUnfrozenEvent.InputTuple, EmergencyUnfrozenEvent.OutputTuple, EmergencyUnfrozenEvent.OutputObject>;
      EmergencyUnfrozen: TypedContractEvent<EmergencyUnfrozenEvent.InputTuple, EmergencyUnfrozenEvent.OutputTuple, EmergencyUnfrozenEvent.OutputObject>;
    

      'Executed(address,uint256,bytes,uint256)': TypedContractEvent<ExecutedEvent.InputTuple, ExecutedEvent.OutputTuple, ExecutedEvent.OutputObject>;
      Executed: TypedContractEvent<ExecutedEvent.InputTuple, ExecutedEvent.OutputTuple, ExecutedEvent.OutputObject>;
    

      'GuardianSet(address)': TypedContractEvent<GuardianSetEvent.InputTuple, GuardianSetEvent.OutputTuple, GuardianSetEvent.OutputObject>;
      GuardianSet: TypedContractEvent<GuardianSetEvent.InputTuple, GuardianSetEvent.OutputTuple, GuardianSetEvent.OutputObject>;
    

      'Locked(uint256)': TypedContractEvent<LockedEvent.InputTuple, LockedEvent.OutputTuple, LockedEvent.OutputObject>;
      Locked: TypedContractEvent<LockedEvent.InputTuple, LockedEvent.OutputTuple, LockedEvent.OutputObject>;
    

      'Received(address,uint256)': TypedContractEvent<ReceivedEvent.InputTuple, ReceivedEvent.OutputTuple, ReceivedEvent.OutputObject>;
      Received: TypedContractEvent<ReceivedEvent.InputTuple, ReceivedEvent.OutputTuple, ReceivedEvent.OutputObject>;
    

      'Swept(address,uint256)': TypedContractEvent<SweptEvent.InputTuple, SweptEvent.OutputTuple, SweptEvent.OutputObject>;
      Swept: TypedContractEvent<SweptEvent.InputTuple, SweptEvent.OutputTuple, SweptEvent.OutputObject>;
    

      'Unlocked()': TypedContractEvent<UnlockedEvent.InputTuple, UnlockedEvent.OutputTuple, UnlockedEvent.OutputObject>;
      Unlocked: TypedContractEvent<UnlockedEvent.InputTuple, UnlockedEvent.OutputTuple, UnlockedEvent.OutputObject>;
    
    };
  }