/* ---------------------------------------------------------------------------
 * 999 Blockchain-Themed Quest Definitions
 *
 * Template-based generation: each zone defines locations, enemies, and lore
 * templates. Quests are generated by combining these components.
 *
 * chain_quest_id = zone_id × 4 + difficulty_index
 *   Easy=0, Medium=1, Hard=2, Boss=3
 *
 * IDs start at 100 to avoid collision with legacy quests (0–31).
 * ------------------------------------------------------------------------- */

export interface QuestSeed {
  id: number;
  name: string;
  zone_id: number;
  difficulty: 'Easy' | 'Medium' | 'Hard' | 'Boss';
  duration_secs: number;
  win_xp: number;
  loss_xp: number;
  min_level: number;
  min_power_score: number;
  base_difficulty: number;
  description: string;
  lore_intro: string;
  lore_success: string;
  lore_failure: string;
  enemy_name: string;
  chain_quest_id: number;
}

export interface ZoneSeed {
  id: number;
  name: string;
  element: string;
  description: string;
  lore: string;
}

/* ---- Zone Definitions (blockchain themed) ---- */

export const ZONE_SEEDS: ZoneSeed[] = [
  {
    id: 0,
    name: 'Genesis Block Forge',
    element: 'Fire',
    description: 'A volcanic forge where the first blocks were minted. Hash power fuels the eternal flame.',
    lore: 'A volcanic forge where the first blocks were minted. Hash power fuels the eternal flame. Ancient miners battle here to crack nonces and claim block rewards.',
  },
  {
    id: 1,
    name: 'Liquidity Abyss',
    element: 'Water',
    description: 'A deep ocean of liquidity pools where DeFi creatures lurk in automated market depths.',
    lore: 'DeFi creatures lurk in the deep ocean of liquidity pools, hiding in automated market depths. The treacherous waters of yield farming await the unwary.',
  },
  {
    id: 2,
    name: 'Gas Storm Peaks',
    element: 'Wind',
    description: 'Sky-piercing peaks where gas fee storms rage and mempool winds howl endlessly.',
    lore: 'Sky-piercing peaks where gas fee storms rage and mempool winds howl endlessly. Every transaction is a struggle against the elements.',
  },
  {
    id: 3,
    name: 'Cold Storage Vaults',
    element: 'Ice',
    description: 'Frozen vaults deep underground where private keys are sealed in permafrost.',
    lore: 'Underground vaults where private keys are sealed in permafrost. A frozen realm protecting cold wallets and dormant assets from all threats.',
  },
  {
    id: 4,
    name: 'Consensus Badlands',
    element: 'Earth',
    description: 'Cracked desert plains where validators stake their claim and governance battles rage.',
    lore: 'Cracked desert plains where validators stake their claim. Lands dominated by PoS mechanisms and fierce governance wars.',
  },
  {
    id: 5,
    name: 'Lightning Network Heights',
    element: 'Thunder',
    description: 'Electrified heights where Layer 2 bridges crackle with cross-chain energy.',
    lore: 'Electrified heights where Layer 2 bridges crackle with cross-chain energy. A realm of lightning-fast transactions and bridge warfare.',
  },
  {
    id: 6,
    name: 'Dark Pool Wastes',
    element: 'Shadow',
    description: 'A twilight wasteland where MEV bots hunt and sandwich attacks lurk in every shadow.',
    lore: 'A twilight wasteland where MEV bots hunt and sandwich attacks lurk in every shadow. The dark realm of frontrunning and hidden transactions.',
  },
  {
    id: 7,
    name: 'Avalanche Summit',
    element: 'Light',
    description: 'The radiant peak of the AVAX ecosystem where subnets converge and C-Chain energy flows.',
    lore: 'The radiant peak of the AVAX ecosystem where subnets converge and C-Chain energy flows. The heart of Avalanche consensus.',
  },
];

/* ---- Difficulty Parameters ---- */

export const DIFF_INDEX: Record<string, number> = { Easy: 0, Medium: 1, Hard: 2, Boss: 3 };

export const DIFF_PARAMS = {
  Easy:   { durations: [300], winXp: 50,  lossXp: 15,  minLevel: 1,  minPowerScore: 0,   baseDifficulty: 80 },
  Medium: { durations: [3600, 4200, 4800, 5400, 6000, 6600, 7200], winXp: 150, lossXp: 40,  minLevel: 3,  minPowerScore: 0,   baseDifficulty: 400 },
  Hard:   { durations: [14400, 16200, 18000, 19800, 21600, 25200, 28800], winXp: 300, lossXp: 75,  minLevel: 7,  minPowerScore: 400, baseDifficulty: 650 },
  Boss:   { durations: [57600, 61200, 64800, 68400, 72000, 79200, 86400], winXp: 600, lossXp: 150, minLevel: 12, minPowerScore: 0,   baseDifficulty: 850 },
} as const;

/* ---- Action verbs per difficulty (shared across zones) ---- */

const EASY_ACTIONS = ['Scout', 'Patrol', 'Sweep', 'Survey', 'Monitor', 'Scan', 'Guard', 'Watch', 'Recon', 'Check'];
const MEDIUM_ACTIONS = ['Hunt', 'Raid', 'Infiltrate', 'Storm', 'Breach', 'Assault', 'Navigate', 'Excavate', 'Pursue', 'Track'];
const HARD_ACTIONS = ['Siege', 'Conquer', 'Vanquish', 'Purge', 'Dominate', 'Overwhelm', 'Devastate', 'Cleanse', 'Annihilate', 'Shatter'];
const BOSS_ACTIONS = ['Fall of', 'Wrath of', 'Trial of', 'Judgment of', 'Reckoning of', 'Downfall of', 'End of', 'Demise of', 'Bane of', 'Doom of'];

export const ACTIONS_BY_DIFF: Record<string, string[]> = {
  Easy: EASY_ACTIONS,
  Medium: MEDIUM_ACTIONS,
  Hard: HARD_ACTIONS,
  Boss: BOSS_ACTIONS,
};

/* ---- Per-zone quest data ---- */

export interface ZoneQuestData {
  targets: string[];       // 8 unique locations within the zone
  enemies: Record<string, string[]>;
  intros: string[];        // Lore intro templates ({enemy} placeholder)
  successes: string[];     // Lore success templates
  failures: string[];      // Lore failure templates
}

export const ZONE_QUEST_DATA: ZoneQuestData[] = [
  /* ---- Zone 0: Genesis Block Forge (Fire) ---- */
  {
    targets: ['Hash Plains', 'Nonce Caves', 'Block Foundry', 'Mining Pit', 'Magma Core', 'Ore Veins', 'Furnace Hall', 'Slag Heap'],
    enemies: {
      Easy:   ['Hash Sprite', 'Nonce Imp', 'Block Dust Mite', 'Mining Rat', 'Spark Fly', 'Cinder Beetle', 'Ash Wisp', 'Ember Tick', 'Coal Crawler', 'Slag Worm'],
      Medium: ['Block Forger', 'Orphan Block Phantom', 'Difficulty Adjuster', 'Hash Rate Golem', 'PoW Guardian', 'Coinbase Sentry', 'Merkle Shade', 'Timestamp Wraith', 'Reward Harvester', 'Chain Splitter'],
      Hard:   ['Hash War Dragon', '51% Colossus', 'Block Reward Wyrm', 'Golden Nonce Titan', 'Difficulty Bomb Entity', 'DAG Director', 'Uncle Block Revenant', 'Fork Storm Beast', 'Hashrate Leviathan', 'Proof-of-Burn Phoenix'],
      Boss:   ['Genesis Block Sovereign', 'The First Miner', "Satoshi's Shadow", 'Hash Singularity', 'The Halving Titan'],
    },
    intros: [
      '{enemy} has been spotted on the Hash Plains. Scout the area and assess the threat.',
      '{enemy} detected deep in the Nonce Caves. Proceed with caution.',
      '{enemy} is disrupting production at the Block Foundry. Intervention required.',
      '{enemy} has emerged in the Mining Pit. Miners are in danger.',
      '{enemy} is gathering power in the Magma Core. Move to intercept.',
      '{enemy} has nested in the Slag Heap. Time for a cleanup.',
      '{enemy} is causing chaos in the Furnace Hall. Restore order.',
      '{enemy} is sabotaging mining operations in the Ore Veins.',
    ],
    successes: [
      '{enemy} defeated! Hash rate has returned to normal.',
      '{enemy} cleared! Block production continues.',
      '{enemy} neutralized! Mining rewards are secure.',
      '{enemy} destroyed! Nonce computation proceeds smoothly.',
      '{enemy} dispersed! The Foundry is back at full capacity.',
    ],
    failures: [
      '{enemy} was too powerful. Hash rate is dropping — fall back!',
      '{enemy} overwhelmed you. Block production has halted.',
      '{enemy} pushed you back. Mining operations suspended.',
      '{enemy} won this round. Regroup and try again stronger.',
      '{enemy} breached the defense. Reassess your strategy.',
    ],
  },

  /* ---- Zone 1: Liquidity Abyss (Water) ---- */
  {
    targets: ['LP Depths', 'Yield Lagoon', 'Swap Reef', 'Token Pool', 'AMM Trench', 'Staking Bay', 'Vault Abyss', 'Farm Delta'],
    enemies: {
      Easy:   ['Rug Pull Minnow', 'Yield Wisp', 'Pool Jellyfish', 'Swap Crab', 'Liquidity Leech', 'Token Eel', 'Drip Sprite', 'Farm Pest', 'APY Guppy', 'Fee Barnacle'],
      Medium: ['Rug Pull Siren', 'Impermanent Loss Shade', 'LP Drainer', 'Yield Vampire', 'Flash Loan Serpent', 'Pool Manipulator', 'AMM Disruptor', 'Slippage Phantom', 'Whale Mimic', 'Vault Breaker'],
      Hard:   ['DeFi Kraken', 'Liquidity Black Hole', 'Oracle Corruptor', 'Protocol Exploiter', 'TVL Devourer', 'Flash Crash Hydra', 'Infinite Mint Serpent', 'Governance Hijacker', 'Reentrancy Beast', 'Drain Attack Leviathan'],
      Boss:   ['The Rug Lord', 'Abyssal Yield Titan', 'Impermanent Loss Sovereign', 'The DeFi Devourer', 'Liquidity Singularity'],
    },
    intros: [
      '{enemy} spotted in the LP Depths. Protect the liquidity pools.',
      '{enemy} is threatening farm operations in Yield Lagoon.',
      '{enemy} is blocking trades at the Swap Reef. Intervene.',
      '{enemy} has appeared in the Token Pool. Investors at risk.',
      '{enemy} lies in ambush in the AMM Trenches. Approach carefully.',
      '{enemy} is targeting staked assets in Staking Bay.',
      '{enemy} is breaking into the Vault Abyss. Stop them!',
      '{enemy} is stealing harvests at the Farm Delta. Protect the farmers.',
    ],
    successes: [
      '{enemy} defeated! Liquidity pools are secure.',
      '{enemy} cleared! Yield farming can resume.',
      '{enemy} neutralized! Swap operations back to normal.',
      '{enemy} destroyed! Token pool protected.',
      '{enemy} dispersed! DeFi protocol is safe.',
    ],
    failures: [
      '{enemy} was too powerful. Liquidity draining — fall back!',
      '{enemy} overwhelmed you. Pools are at risk.',
      '{enemy} got the better of you. Impermanent loss risk rising.',
      '{enemy} won. Assets are in danger.',
      '{enemy} breached the defense. Reinforce the protocol.',
    ],
  },

  /* ---- Zone 2: Gas Storm Peaks (Wind) ---- */
  {
    targets: ['Mempool Ridge', 'Gas Crater', 'Priority Canyon', 'Fee Tornado Alley', 'EIP Summit', 'Pending Valley', 'Block Space Mesa', 'Nonce Gap Cliff'],
    enemies: {
      Easy:   ['Gas Fee Phantom', 'Mempool Gnat', 'Pending Tx Wisp', 'Fee Spike Beetle', 'Low Gas Spirit', 'Nonce Gap Imp', 'Block Space Moth', 'Priority Weasel', 'Stuck Tx Sprite', 'Congestion Mite'],
      Medium: ['Mempool Swarmer', 'Gas War Commander', 'Fee Market Golem', 'Block Space Hoarder', 'Priority Fee Hunter', 'EIP Enforcer', 'Nonce Manager', 'Revert Stalker', 'Congestion Serpent', 'Base Fee Adjuster'],
      Hard:   ['Gas Storm Dragon', 'Mempool Overflow Titan', 'Fee Spike Colossus', 'Block Space Monopolist', 'Gas Limit Breaker', 'Transaction Storm Wyrm', 'Congestion Hydra', 'Failed Tx Reaper', 'Gas Oracle Corruptor', 'EIP Destroyer'],
      Boss:   ['The Gas Singularity', 'Mempool Sovereign', 'Storm Fee Titan', 'The Eternal Congestion', 'Block Space Devourer'],
    },
    intros: [
      '{enemy} spotted on Mempool Ridge. Protect transaction traffic.',
      '{enemy} is manipulating fees at the Gas Crater.',
      '{enemy} is blocking priority transactions in Priority Canyon.',
      '{enemy} is whipping up a storm in Fee Tornado Alley.',
      '{enemy} is sabotaging protocol upgrades at EIP Summit.',
      '{enemy} is destroying pending transactions in Pending Valley.',
      '{enemy} is monopolizing block space at Block Space Mesa.',
      '{enemy} is creating nonce gaps at Nonce Gap Cliff.',
    ],
    successes: [
      '{enemy} defeated! Gas fees have normalized.',
      '{enemy} cleared! Mempool flow restored.',
      '{enemy} neutralized! Transactions going through smoothly.',
      '{enemy} destroyed! Block space freed.',
      '{enemy} dispersed! Congestion resolved.',
    ],
    failures: [
      '{enemy} was too powerful. Gas fees spiking — fall back!',
      '{enemy} overwhelmed you. Mempool is congested.',
      '{enemy} pushed you back. Transactions are failing.',
      '{enemy} won. Block space is shrinking.',
      '{enemy} breached the defense. Congestion is increasing.',
    ],
  },

  /* ---- Zone 3: Cold Storage Vaults (Ice) ---- */
  {
    targets: ['Seed Phrase Cavern', 'Private Key Glacier', 'Hardware Vault', 'Frozen Ledger', 'Backup Crypt', 'Multisig Fortress', 'Air-Gap Chamber', 'Recovery Tundra'],
    enemies: {
      Easy:   ['Frost Key Spirit', 'Phishing Imp', 'Clipboard Hijacker', 'Seed Sprite', 'Cold Dust Mite', 'Frozen Byte Bug', 'Ice Shard Crawler', 'Permafrost Rat', 'Key Logger Tick', 'Brute Force Wisp'],
      Medium: ['Seed Phrase Wraith', 'Private Key Hunter', 'SIM Swap Phantom', 'Social Engineer', 'Wallet Drainer', 'Evil Maid Golem', 'Supply Chain Shade', '2FA Bypasser', 'Firmware Corruptor', 'Backup Breacher'],
      Hard:   ['Cold Storage Dragon', 'Master Key Titan', 'Quantum Key Breaker', 'Hardware Exploiter', 'Multisig Infiltrator', 'Side Channel Wyrm', 'Air-Gap Violator', 'Entropy Destroyer', 'Cryptographic Beast', 'Recovery Annihilator'],
      Boss:   ['The Key Master', 'Absolute Zero Sovereign', 'Quantum Decryptor', 'The Vault Breaker Supreme', 'Frozen Eternity'],
    },
    intros: [
      '{enemy} detected in the Seed Phrase Cavern. Protect the keys.',
      '{enemy} is attempting infiltration at the Private Key Glacier.',
      '{enemy} is probing for vulnerabilities in the Hardware Vault.',
      '{enemy} is trying to alter records in the Frozen Ledger.',
      '{enemy} is targeting recovery phrases in the Backup Crypt.',
      '{enemy} is manipulating signers at the Multisig Fortress.',
      '{enemy} is trying to breach isolation in the Air-Gap Chamber.',
      '{enemy} is blocking recovery processes in the Recovery Tundra.',
    ],
    successes: [
      '{enemy} defeated! Private keys are secure.',
      '{enemy} cleared! Cold storage integrity preserved.',
      '{enemy} neutralized! Seed phrase is safe.',
      '{enemy} destroyed! Vaults remain intact.',
      '{enemy} dispersed! Assets protected.',
    ],
    failures: [
      '{enemy} was too powerful. Security breach risk — fall back!',
      '{enemy} overwhelmed you. Keys are at risk.',
      '{enemy} got the better of you. Check your backups.',
      '{enemy} won. Cold storage needs reinforcement.',
      '{enemy} breached the defense. Initiate emergency procedures.',
    ],
  },

  /* ---- Zone 4: Consensus Badlands (Earth) ---- */
  {
    targets: ['Validator Plains', 'Staking Quarry', 'Governance Hall', 'Epoch Badlands', 'Delegation Mesa', 'Slashing Gorge', 'Proposal Ridge', 'Finality Desert'],
    enemies: {
      Easy:   ['Rogue Validator Pup', 'Delegation Rat', 'Stake Dust Mite', 'Epoch Beetle', 'Vote Wisp', 'Governance Imp', 'Penalty Sprite', 'Uptime Gnat', 'Attestation Bug', 'Sync Worm'],
      Medium: ['Rogue Validator', 'Slashing Sentinel', 'Governance Manipulator', 'Nothing-at-Stake Ghost', 'Long Range Attacker', 'Censorship Golem', 'Delegation Thief', 'Epoch Disruptor', 'Committee Infiltrator', 'Finality Blocker'],
      Hard:   ['Validator Cartel Boss', 'Consensus Break Titan', '34% Attack Dragon', 'Governance Hijacker', 'Stake Centralization Wyrm', 'Liveness Destroyer', 'Safety Violation Beast', 'Fork Choice Corruptor', 'MEV Validator Lord', 'Proposer Extractor'],
      Boss:   ['The Consensus Breaker', 'Absolute Stake Sovereign', 'Governance Singularity', 'The Finality Destroyer', 'Epoch Zero Titan'],
    },
    intros: [
      '{enemy} spotted on the Validator Plains. Protect the consensus.',
      '{enemy} is targeting staked assets in the Staking Quarry.',
      '{enemy} is manipulating the voting process in Governance Hall.',
      '{enemy} is disrupting epoch transitions in the Epoch Badlands.',
      '{enemy} is stealing delegations at Delegation Mesa.',
      '{enemy} is exploiting the penalty mechanism in Slashing Gorge.',
      '{enemy} is sabotaging governance proposals at Proposal Ridge.',
      '{enemy} is blocking finality in the Finality Desert.',
    ],
    successes: [
      '{enemy} defeated! Consensus mechanism protected.',
      '{enemy} cleared! Validators are safe.',
      '{enemy} neutralized! Staking rewards are secure.',
      '{enemy} destroyed! Governance process continues.',
      '{enemy} dispersed! Network security ensured.',
    ],
    failures: [
      '{enemy} was too powerful. Consensus at risk — fall back!',
      '{enemy} overwhelmed you. Validators are in danger.',
      '{enemy} pushed you back. Staked assets at risk.',
      '{enemy} won. Governance process disrupted.',
      '{enemy} breached the defense. Restore network security.',
    ],
  },

  /* ---- Zone 5: Lightning Network Heights (Thunder) ---- */
  {
    targets: ['Bridge Gateway', 'Channel Spire', 'Relay Tower', 'Rollup Summit', 'Sidechain Pass', 'State Channel', 'Cross-Chain Nexus', 'L2 Beacon'],
    enemies: {
      Easy:   ['Bridge Troll', 'Channel Spark', 'Relay Gremlin', 'Rollup Rat', 'Sidechain Sprite', 'State Tick', 'Cross-Chain Imp', 'L2 Buzz', 'Sync Beetle', 'Proof Wisp'],
      Medium: ['Bridge Exploiter', 'Channel Breaker', 'Relay Saboteur', 'Rollup Manipulator', 'Sidechain Corruptor', 'State Root Forger', 'Cross-Chain Phantom', 'Fraud Proof Dodger', 'Sequencer Hijacker', 'Withdrawal Blocker'],
      Hard:   ['Bridge Collapse Dragon', 'Channel Storm Titan', 'Relay Chain Destroyer', 'Rollup Escape Wyrm', 'Sidechain Severer', 'Validity Proof Annihilator', 'Cross-Chain Leviathan', 'L2 Congestion Beast', 'Forced Exit Executor', 'Data Availability Breaker'],
      Boss:   ['The Bridge Breaker Supreme', 'Lightning Sovereign', 'Cross-Chain Singularity', 'The L2 Devourer', 'Interoperability Titan'],
    },
    intros: [
      '{enemy} is blocking cross-chain transfers at the Bridge Gateway.',
      '{enemy} is shutting down payment channels at Channel Spire.',
      '{enemy} is sabotaging message relay at the Relay Tower.',
      '{enemy} is corrupting batch transactions at Rollup Summit.',
      '{enemy} is severing sidechain connections at Sidechain Pass.',
      '{enemy} is manipulating state updates in the State Channel.',
      '{enemy} is blocking cross-chain traffic at the Cross-Chain Nexus.',
      '{enemy} is threatening Layer 2 operations at the L2 Beacon.',
    ],
    successes: [
      '{enemy} defeated! Bridge connections restored.',
      '{enemy} cleared! Lightning channels are open.',
      '{enemy} neutralized! Cross-chain transfers continue.',
      '{enemy} destroyed! L2 operations back to normal.',
      '{enemy} dispersed! Cross-chain communication is secure.',
    ],
    failures: [
      '{enemy} was too powerful. Bridge connections failing — fall back!',
      '{enemy} overwhelmed you. Channels are closing.',
      '{enemy} got the better of you. Cross-chain transfers failed.',
      '{enemy} won. L2 operations halted.',
      '{enemy} breached the defense. Rebuild cross-chain connections.',
    ],
  },

  /* ---- Zone 6: Dark Pool Wastes (Shadow) ---- */
  {
    targets: ['MEV Forest', 'Frontrun Alley', 'Sandwich Pit', 'Exploit Cavern', 'Flashbot Lair', 'Arbitrage Ruins', 'Liquidation Zone', 'Dark Mempool'],
    enemies: {
      Easy:   ['MEV Bot Scout', 'Frontrun Imp', 'Sandwich Tick', 'Exploit Rat', 'Flashbot Sprite', 'Arb Beetle', 'Liquidation Wisp', 'Dark Tx Mite', 'Sniper Gnat', 'Copy Trader Bug'],
      Medium: ['MEV Bot Assassin', 'Sandwich Stalker', 'Frontrun Phantom', 'Exploit Developer', 'Flashbot Commander', 'Arbitrage Golem', 'Liquidation Hunter', 'Dark Pool Sentry', 'Backrun Serpent', 'JIT Liquidity Shade'],
      Hard:   ['MEV Extraction Dragon', 'Sandwich Attack Titan', 'Frontrun Colossus', 'Zero-Day Exploiter', 'Flashbot Army General', 'Arbitrage Overlord', 'Liquidation Cascade Wyrm', 'Time-Bandit Attacker', 'Oracle Manipulation Beast', 'Reentrancy Master'],
      Boss:   ['The MEV King', 'Dark Pool Sovereign', 'The Sandwich Emperor', 'Exploit Singularity', 'Shadow Mempool Lord'],
    },
    intros: [
      '{enemy} is monitoring transactions in the MEV Forest. Stay alert in the dark.',
      '{enemy} is planning frontrun attacks in Frontrun Alley.',
      '{enemy} is preparing a sandwich attack in the Sandwich Pit.',
      '{enemy} is searching for new exploits in the Exploit Cavern.',
      '{enemy} controls hidden channels in the Flashbot Lair.',
      '{enemy} is exploiting price gaps in the Arbitrage Ruins.',
      '{enemy} is hunting liquidation opportunities in the Liquidation Zone.',
      '{enemy} is executing covert transactions in the Dark Mempool.',
    ],
    successes: [
      '{enemy} defeated! MEV threat eliminated.',
      '{enemy} cleared! Transactions are safe.',
      '{enemy} neutralized! Sandwich attacks stopped.',
      '{enemy} destroyed! Exploit patched.',
      '{enemy} dispersed! Dark pool cleaned.',
    ],
    failures: [
      '{enemy} was too cunning. MEV loss sustained — fall back!',
      '{enemy} sandwiched you. Assets at risk.',
      '{enemy} frontran you. Change strategy.',
      '{enemy} won. Exploit still active.',
      '{enemy} vanished into the shadows. Tracking impossible.',
    ],
  },

  /* ---- Zone 7: Avalanche Summit (Light) ---- */
  {
    targets: ['C-Chain Plaza', 'Subnet Gateway', 'Validator Peak', 'Snowman Shrine', 'AVAX Core', 'Warp Messenger Hall', 'P-Chain Citadel', 'X-Chain Bazaar'],
    enemies: {
      Easy:   ['Subnet Sprite', 'Chain Dust Wisp', 'AVAX Spark', 'Validator Imp', 'Warp Message Bug', 'P-Chain Mite', 'X-Chain Beetle', 'Snow Tick', 'Consensus Gnat', 'Gas Token Fly'],
      Medium: ['Subnet Corruptor', 'Chain Splitter', 'AVAX Drainer', 'Rogue Subnet Operator', 'Warp Interceptor', 'P-Chain Manipulator', 'X-Chain Disruptor', 'Snowman Shade', 'HyperSDK Saboteur', 'Teleporter Hijacker'],
      Hard:   ['Subnet Overlord', 'C-Chain Storm Dragon', 'AVAX Hoarding Titan', 'Multi-Chain Destroyer', 'Consensus Storm Wyrm', 'Warp Attack Colossus', 'P-Chain Siege Engine', 'X-Chain Annihilator', 'Elastic Subnet Beast', 'Validator Centralization Lord'],
      Boss:   ['The Subnet Sovereign', 'Avalanche Apex Titan', 'C-Chain Singularity', 'The AVAX Devourer', 'Consensus Eternal'],
    },
    intros: [
      '{enemy} is disrupting transaction traffic at C-Chain Plaza. Intervene.',
      '{enemy} is threatening subnet connections at the Subnet Gateway.',
      '{enemy} is blocking the validation process at Validator Peak.',
      '{enemy} is targeting the AVAX ecosystem at the Snowman Shrine.',
      '{enemy} is threatening the core protocol at AVAX Core.',
      '{enemy} is blocking cross-chain messages at Warp Messenger Hall.',
      '{enemy} is sabotaging the platform chain at P-Chain Citadel.',
      '{enemy} is blocking transfers at the X-Chain Bazaar.',
    ],
    successes: [
      '{enemy} defeated! AVAX ecosystem is secure.',
      '{enemy} cleared! Subnets running smoothly.',
      '{enemy} neutralized! C-Chain protected.',
      '{enemy} destroyed! Validators standing strong.',
      '{enemy} dispersed! Avalanche consensus holds firm.',
    ],
    failures: [
      '{enemy} was too powerful. AVAX network slowing — fall back!',
      '{enemy} overwhelmed you. Subnet connections severed.',
      '{enemy} got the better of you. C-Chain performance degraded.',
      '{enemy} won. Validator set at risk.',
      '{enemy} breached the defense. Reinforce the ecosystem.',
    ],
  },
];

/* ---- Quest Generator ---- */

// Boss tier modifiers for repeated cycles (5 bosses × 4 tiers = 20 unique names)
const BOSS_TIERS = ['', 'Enraged ', 'Awakened ', 'Ascended '];

export function generateAllQuests(): QuestSeed[] {
  const quests: QuestSeed[] = [];
  let nextId = 100;

  for (let zoneId = 0; zoneId < 8; zoneId++) {
    const data = ZONE_QUEST_DATA[zoneId];
    const perDiff: { diff: 'Easy' | 'Medium' | 'Hard' | 'Boss'; count: number }[] = [
      { diff: 'Easy', count: 40 },
      { diff: 'Medium', count: 35 },
      { diff: 'Hard', count: 30 },
      // Last zone has 19 Boss quests to reach 999 total
      { diff: 'Boss', count: zoneId === 7 ? 19 : 20 },
    ];

    for (const { diff, count } of perDiff) {
      const params = DIFF_PARAMS[diff];
      const actions = ACTIONS_BY_DIFF[diff];
      const enemies = data.enemies[diff];
      const chainQuestId = zoneId * 4 + DIFF_INDEX[diff];

      for (let i = 0; i < count; i++) {
        const action = actions[i % actions.length];
        const target = data.targets[i % data.targets.length];
        const duration = params.durations[i % params.durations.length];

        // For Boss, add tier prefix to enemy name for uniqueness across cycles
        let enemy: string;
        if (diff === 'Boss') {
          const cycle = Math.floor(i / enemies.length);
          const tier = BOSS_TIERS[cycle] ?? `Phase ${cycle + 1} `;
          enemy = cycle === 0 ? enemies[i % enemies.length] : `${tier}${enemies[i % enemies.length]}`;
        } else {
          enemy = enemies[i % enemies.length];
        }

        // Boss quests use "{action} {enemy}" format, others use "{action} {target}"
        const name = diff === 'Boss'
          ? `${action} ${enemy}`
          : `${action} ${target}`;

        const description = diff === 'Boss'
          ? `Face the legendary ${enemy} in an epic battle at the heart of ${ZONE_SEEDS[zoneId].name}.`
          : `${action} operation in ${target}. Defeat ${enemy} forces threatening the area.`;

        quests.push({
          id: nextId++,
          name,
          zone_id: zoneId,
          difficulty: diff,
          duration_secs: duration,
          win_xp: params.winXp,
          loss_xp: params.lossXp,
          min_level: params.minLevel,
          min_power_score: params.minPowerScore,
          base_difficulty: params.baseDifficulty,
          description,
          lore_intro: data.intros[i % data.intros.length].replace('{enemy}', enemy),
          lore_success: data.successes[i % data.successes.length].replace('{enemy}', enemy),
          lore_failure: data.failures[i % data.failures.length].replace('{enemy}', enemy),
          enemy_name: enemy,
          chain_quest_id: chainQuestId,
        });
      }
    }
  }

  return quests;
}
