/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IArenaWarriorTeam } from './IArenaWarriorTeam.js';
export type { TeamBattleEngine } from './TeamBattleEngine.js';