/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface TeamBattleEngineInterface extends Interface {
    getFunction(nameOrSignature: "ATTACK_WEIGHT" | "BASIS_POINTS" | "BATTLE_TIMEOUT" | "DEFENSE_WEIGHT" | "ELEMENT_EARTH" | "ELEMENT_FIRE" | "ELEMENT_ICE" | "ELEMENT_LIGHT" | "ELEMENT_SHADOW" | "ELEMENT_THUNDER" | "ELEMENT_WATER" | "ELEMENT_WIND" | "FEE_BASIS_POINTS" | "LOSS_EXPERIENCE" | "MIN_STAKE" | "SPECIAL_WEIGHT" | "SPEED_WEIGHT" | "TEAM_SIZE" | "UPGRADE_INTERFACE_VERSION" | "WINS_TO_WIN" | "WIN_EXPERIENCE" | "accumulatedFees" | "addAdmin" | "admins" | "arenaWarrior" | "battleCounter" | "cancelTeamBattle" | "claimTimeout" | "createTeamBattle" | "feeRecipient" | "getOpenTeamBattleCount" | "getOpenTeamBattles" | "getPlatformStats" | "getPlayerTeamBattleCount" | "getPlayerTeamBattlesPaginated" | "getResolvedTeamBattleCount" | "getResolvedTeamBattles" | "getTeamBattle" | "getTeamBattleHistory" | "initialize" | "joinTeamBattle" | "nonces" | "owner" | "pause" | "paused" | "proxiableUUID" | "removeAdmin" | "renounceOwnership" | "setArenaWarrior" | "setFeeRecipient" | "setTrustedSigner" | "teamBattles" | "totalWagered" | "transferOwnership" | "trustedSigner" | "unpause" | "upgradeToAndCall" | "withdrawFees"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "AdminAdded" | "AdminRemoved" | "ContractPaused" | "ContractUnpaused" | "Initialized" | "OwnershipTransferred" | "Paused" | "TeamBattleCancelled" | "TeamBattleCreated" | "TeamBattleJoined" | "TeamBattleResolved" | "TrustedSignerUpdated" | "Unpaused" | "Upgraded"): EventFragment;

    encodeFunctionData(functionFragment: 'ATTACK_WEIGHT', values?: undefined): string;
encodeFunctionData(functionFragment: 'BASIS_POINTS', values?: undefined): string;
encodeFunctionData(functionFragment: 'BATTLE_TIMEOUT', values?: undefined): string;
encodeFunctionData(functionFragment: 'DEFENSE_WEIGHT', values?: undefined): string;
encodeFunctionData(functionFragment: 'ELEMENT_EARTH', values?: undefined): string;
encodeFunctionData(functionFragment: 'ELEMENT_FIRE', values?: undefined): string;
encodeFunctionData(functionFragment: 'ELEMENT_ICE', values?: undefined): string;
encodeFunctionData(functionFragment: 'ELEMENT_LIGHT', values?: undefined): string;
encodeFunctionData(functionFragment: 'ELEMENT_SHADOW', values?: undefined): string;
encodeFunctionData(functionFragment: 'ELEMENT_THUNDER', values?: undefined): string;
encodeFunctionData(functionFragment: 'ELEMENT_WATER', values?: undefined): string;
encodeFunctionData(functionFragment: 'ELEMENT_WIND', values?: undefined): string;
encodeFunctionData(functionFragment: 'FEE_BASIS_POINTS', values?: undefined): string;
encodeFunctionData(functionFragment: 'LOSS_EXPERIENCE', values?: undefined): string;
encodeFunctionData(functionFragment: 'MIN_STAKE', values?: undefined): string;
encodeFunctionData(functionFragment: 'SPECIAL_WEIGHT', values?: undefined): string;
encodeFunctionData(functionFragment: 'SPEED_WEIGHT', values?: undefined): string;
encodeFunctionData(functionFragment: 'TEAM_SIZE', values?: undefined): string;
encodeFunctionData(functionFragment: 'UPGRADE_INTERFACE_VERSION', values?: undefined): string;
encodeFunctionData(functionFragment: 'WINS_TO_WIN', values?: undefined): string;
encodeFunctionData(functionFragment: 'WIN_EXPERIENCE', values?: undefined): string;
encodeFunctionData(functionFragment: 'accumulatedFees', values?: undefined): string;
encodeFunctionData(functionFragment: 'addAdmin', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'admins', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'arenaWarrior', values?: undefined): string;
encodeFunctionData(functionFragment: 'battleCounter', values?: undefined): string;
encodeFunctionData(functionFragment: 'cancelTeamBattle', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'claimTimeout', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'createTeamBattle', values: [[BigNumberish, BigNumberish, BigNumberish], BytesLike]): string;
encodeFunctionData(functionFragment: 'feeRecipient', values?: undefined): string;
encodeFunctionData(functionFragment: 'getOpenTeamBattleCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'getOpenTeamBattles', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getPlatformStats', values?: undefined): string;
encodeFunctionData(functionFragment: 'getPlayerTeamBattleCount', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getPlayerTeamBattlesPaginated', values: [AddressLike, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getResolvedTeamBattleCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'getResolvedTeamBattles', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getTeamBattle', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getTeamBattleHistory', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'initialize', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'joinTeamBattle', values: [BigNumberish, [BigNumberish, BigNumberish, BigNumberish], BytesLike]): string;
encodeFunctionData(functionFragment: 'nonces', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'pause', values?: undefined): string;
encodeFunctionData(functionFragment: 'paused', values?: undefined): string;
encodeFunctionData(functionFragment: 'proxiableUUID', values?: undefined): string;
encodeFunctionData(functionFragment: 'removeAdmin', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'setArenaWarrior', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setFeeRecipient', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setTrustedSigner', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'teamBattles', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'totalWagered', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'trustedSigner', values?: undefined): string;
encodeFunctionData(functionFragment: 'unpause', values?: undefined): string;
encodeFunctionData(functionFragment: 'upgradeToAndCall', values: [AddressLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'withdrawFees', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'ATTACK_WEIGHT', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'BASIS_POINTS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'BATTLE_TIMEOUT', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'DEFENSE_WEIGHT', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'ELEMENT_EARTH', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'ELEMENT_FIRE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'ELEMENT_ICE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'ELEMENT_LIGHT', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'ELEMENT_SHADOW', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'ELEMENT_THUNDER', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'ELEMENT_WATER', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'ELEMENT_WIND', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'FEE_BASIS_POINTS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'LOSS_EXPERIENCE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MIN_STAKE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'SPECIAL_WEIGHT', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'SPEED_WEIGHT', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'TEAM_SIZE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'UPGRADE_INTERFACE_VERSION', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'WINS_TO_WIN', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'WIN_EXPERIENCE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'accumulatedFees', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'addAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'admins', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'arenaWarrior', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'battleCounter', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'cancelTeamBattle', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'claimTimeout', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createTeamBattle', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'feeRecipient', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getOpenTeamBattleCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getOpenTeamBattles', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPlatformStats', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPlayerTeamBattleCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPlayerTeamBattlesPaginated', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getResolvedTeamBattleCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getResolvedTeamBattles', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTeamBattle', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTeamBattleHistory', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'initialize', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'joinTeamBattle', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'nonces', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pause', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'paused', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'proxiableUUID', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'removeAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setArenaWarrior', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setFeeRecipient', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setTrustedSigner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'teamBattles', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalWagered', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'trustedSigner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unpause', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'upgradeToAndCall', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdrawFees', data: BytesLike): Result;
  }

  
    export namespace AdminAddedEvent {
      export type InputTuple = [admin: AddressLike];
      export type OutputTuple = [admin: string];
      export interface OutputObject {admin: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace AdminRemovedEvent {
      export type InputTuple = [admin: AddressLike];
      export type OutputTuple = [admin: string];
      export interface OutputObject {admin: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ContractPausedEvent {
      export type InputTuple = [by: AddressLike];
      export type OutputTuple = [by: string];
      export interface OutputObject {by: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ContractUnpausedEvent {
      export type InputTuple = [by: AddressLike];
      export type OutputTuple = [by: string];
      export interface OutputObject {by: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace InitializedEvent {
      export type InputTuple = [version: BigNumberish];
      export type OutputTuple = [version: bigint];
      export interface OutputObject {version: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TeamBattleCancelledEvent {
      export type InputTuple = [battleId: BigNumberish, player: AddressLike];
      export type OutputTuple = [battleId: bigint, player: string];
      export interface OutputObject {battleId: bigint, player: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TeamBattleCreatedEvent {
      export type InputTuple = [battleId: BigNumberish, player1: AddressLike, team: [BigNumberish, BigNumberish, BigNumberish], stake: BigNumberish];
      export type OutputTuple = [battleId: bigint, player1: string, team: [bigint, bigint, bigint], stake: bigint];
      export interface OutputObject {battleId: bigint, player1: string, team: [bigint, bigint, bigint], stake: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TeamBattleJoinedEvent {
      export type InputTuple = [battleId: BigNumberish, player2: AddressLike, team: [BigNumberish, BigNumberish, BigNumberish]];
      export type OutputTuple = [battleId: bigint, player2: string, team: [bigint, bigint, bigint]];
      export interface OutputObject {battleId: bigint, player2: string, team: [bigint, bigint, bigint] };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TeamBattleResolvedEvent {
      export type InputTuple = [battleId: BigNumberish, winner: AddressLike, loser: AddressLike, score1: BigNumberish, score2: BigNumberish, payout: BigNumberish];
      export type OutputTuple = [battleId: bigint, winner: string, loser: string, score1: bigint, score2: bigint, payout: bigint];
      export interface OutputObject {battleId: bigint, winner: string, loser: string, score1: bigint, score2: bigint, payout: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TrustedSignerUpdatedEvent {
      export type InputTuple = [signer: AddressLike];
      export type OutputTuple = [signer: string];
      export interface OutputObject {signer: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UnpausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UpgradedEvent {
      export type InputTuple = [implementation: AddressLike];
      export type OutputTuple = [implementation: string];
      export interface OutputObject {implementation: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface TeamBattleEngine extends BaseContract {
    
    connect(runner?: ContractRunner | null): TeamBattleEngine;
    waitForDeployment(): Promise<this>;

    interface: TeamBattleEngineInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    ATTACK_WEIGHT: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    BASIS_POINTS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    BATTLE_TIMEOUT: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    DEFENSE_WEIGHT: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    ELEMENT_EARTH: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    ELEMENT_FIRE: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    ELEMENT_ICE: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    ELEMENT_LIGHT: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    ELEMENT_SHADOW: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    ELEMENT_THUNDER: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    ELEMENT_WATER: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    ELEMENT_WIND: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    FEE_BASIS_POINTS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    LOSS_EXPERIENCE: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MIN_STAKE: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    SPECIAL_WEIGHT: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    SPEED_WEIGHT: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    TEAM_SIZE: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    UPGRADE_INTERFACE_VERSION: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    WINS_TO_WIN: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    WIN_EXPERIENCE: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    accumulatedFees: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    addAdmin: TypedContractMethod<
      [admin: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    admins: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    arenaWarrior: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    battleCounter: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    cancelTeamBattle: TypedContractMethod<
      [battleId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    claimTimeout: TypedContractMethod<
      [battleId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    createTeamBattle: TypedContractMethod<
      [tokenIds: [BigNumberish, BigNumberish, BigNumberish], signature: BytesLike, ],
      [void],
      'payable'
    >
    

    
    feeRecipient: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    getOpenTeamBattleCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getOpenTeamBattles: TypedContractMethod<
      [offset: BigNumberish, limit: BigNumberish, ],
      [bigint[]],
      'view'
    >
    

    
    getPlatformStats: TypedContractMethod<
      [],
      [[bigint, bigint, bigint] & {_totalBattles: bigint, _totalWagered: bigint, _totalFees: bigint }],
      'view'
    >
    

    
    getPlayerTeamBattleCount: TypedContractMethod<
      [player: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    getPlayerTeamBattlesPaginated: TypedContractMethod<
      [player: AddressLike, offset: BigNumberish, limit: BigNumberish, ],
      [bigint[]],
      'view'
    >
    

    
    getResolvedTeamBattleCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getResolvedTeamBattles: TypedContractMethod<
      [offset: BigNumberish, limit: BigNumberish, ],
      [bigint[]],
      'view'
    >
    

    
    getTeamBattle: TypedContractMethod<
      [battleId: BigNumberish, ],
      [[bigint, string, string, [bigint, bigint, bigint], [bigint, bigint, bigint], bigint, bigint, bigint, [bigint, bigint, bigint], string, boolean, bigint, bigint] & {id: bigint, player1: string, player2: string, team1: [bigint, bigint, bigint], team2: [bigint, bigint, bigint], stake: bigint, score1: bigint, score2: bigint, matchups: [bigint, bigint, bigint], winner: string, resolved: boolean, createdAt: bigint, resolvedAt: bigint }],
      'view'
    >
    

    
    getTeamBattleHistory: TypedContractMethod<
      [player: AddressLike, ],
      [bigint[]],
      'view'
    >
    

    
    initialize: TypedContractMethod<
      [_arenaWarrior: AddressLike, _feeRecipient: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    joinTeamBattle: TypedContractMethod<
      [battleId: BigNumberish, tokenIds: [BigNumberish, BigNumberish, BigNumberish], signature: BytesLike, ],
      [void],
      'payable'
    >
    

    
    nonces: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    pause: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    paused: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    proxiableUUID: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    removeAdmin: TypedContractMethod<
      [admin: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    setArenaWarrior: TypedContractMethod<
      [_arenaWarrior: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setFeeRecipient: TypedContractMethod<
      [_feeRecipient: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setTrustedSigner: TypedContractMethod<
      [_signer: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    teamBattles: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, string, bigint, bigint, bigint, string, boolean, bigint, bigint] & {id: bigint, player1: string, player2: string, stake: bigint, score1: bigint, score2: bigint, winner: string, resolved: boolean, createdAt: bigint, resolvedAt: bigint }],
      'view'
    >
    

    
    totalWagered: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    trustedSigner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    unpause: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    upgradeToAndCall: TypedContractMethod<
      [newImplementation: AddressLike, data: BytesLike, ],
      [void],
      'payable'
    >
    

    
    withdrawFees: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'ATTACK_WEIGHT'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'BASIS_POINTS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'BATTLE_TIMEOUT'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'DEFENSE_WEIGHT'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'ELEMENT_EARTH'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'ELEMENT_FIRE'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'ELEMENT_ICE'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'ELEMENT_LIGHT'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'ELEMENT_SHADOW'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'ELEMENT_THUNDER'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'ELEMENT_WATER'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'ELEMENT_WIND'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'FEE_BASIS_POINTS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'LOSS_EXPERIENCE'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MIN_STAKE'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'SPECIAL_WEIGHT'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'SPEED_WEIGHT'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'TEAM_SIZE'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'UPGRADE_INTERFACE_VERSION'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'WINS_TO_WIN'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'WIN_EXPERIENCE'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'accumulatedFees'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'addAdmin'): TypedContractMethod<
      [admin: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'admins'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'arenaWarrior'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'battleCounter'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'cancelTeamBattle'): TypedContractMethod<
      [battleId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'claimTimeout'): TypedContractMethod<
      [battleId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createTeamBattle'): TypedContractMethod<
      [tokenIds: [BigNumberish, BigNumberish, BigNumberish], signature: BytesLike, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'feeRecipient'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getOpenTeamBattleCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getOpenTeamBattles'): TypedContractMethod<
      [offset: BigNumberish, limit: BigNumberish, ],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'getPlatformStats'): TypedContractMethod<
      [],
      [[bigint, bigint, bigint] & {_totalBattles: bigint, _totalWagered: bigint, _totalFees: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'getPlayerTeamBattleCount'): TypedContractMethod<
      [player: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getPlayerTeamBattlesPaginated'): TypedContractMethod<
      [player: AddressLike, offset: BigNumberish, limit: BigNumberish, ],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'getResolvedTeamBattleCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getResolvedTeamBattles'): TypedContractMethod<
      [offset: BigNumberish, limit: BigNumberish, ],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'getTeamBattle'): TypedContractMethod<
      [battleId: BigNumberish, ],
      [[bigint, string, string, [bigint, bigint, bigint], [bigint, bigint, bigint], bigint, bigint, bigint, [bigint, bigint, bigint], string, boolean, bigint, bigint] & {id: bigint, player1: string, player2: string, team1: [bigint, bigint, bigint], team2: [bigint, bigint, bigint], stake: bigint, score1: bigint, score2: bigint, matchups: [bigint, bigint, bigint], winner: string, resolved: boolean, createdAt: bigint, resolvedAt: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'getTeamBattleHistory'): TypedContractMethod<
      [player: AddressLike, ],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'initialize'): TypedContractMethod<
      [_arenaWarrior: AddressLike, _feeRecipient: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'joinTeamBattle'): TypedContractMethod<
      [battleId: BigNumberish, tokenIds: [BigNumberish, BigNumberish, BigNumberish], signature: BytesLike, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'nonces'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'pause'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'paused'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'proxiableUUID'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'removeAdmin'): TypedContractMethod<
      [admin: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setArenaWarrior'): TypedContractMethod<
      [_arenaWarrior: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setFeeRecipient'): TypedContractMethod<
      [_feeRecipient: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setTrustedSigner'): TypedContractMethod<
      [_signer: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'teamBattles'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, string, bigint, bigint, bigint, string, boolean, bigint, bigint] & {id: bigint, player1: string, player2: string, stake: bigint, score1: bigint, score2: bigint, winner: string, resolved: boolean, createdAt: bigint, resolvedAt: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'totalWagered'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'trustedSigner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'unpause'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'upgradeToAndCall'): TypedContractMethod<
      [newImplementation: AddressLike, data: BytesLike, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'withdrawFees'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'AdminAdded'): TypedContractEvent<AdminAddedEvent.InputTuple, AdminAddedEvent.OutputTuple, AdminAddedEvent.OutputObject>;
getEvent(key: 'AdminRemoved'): TypedContractEvent<AdminRemovedEvent.InputTuple, AdminRemovedEvent.OutputTuple, AdminRemovedEvent.OutputObject>;
getEvent(key: 'ContractPaused'): TypedContractEvent<ContractPausedEvent.InputTuple, ContractPausedEvent.OutputTuple, ContractPausedEvent.OutputObject>;
getEvent(key: 'ContractUnpaused'): TypedContractEvent<ContractUnpausedEvent.InputTuple, ContractUnpausedEvent.OutputTuple, ContractUnpausedEvent.OutputObject>;
getEvent(key: 'Initialized'): TypedContractEvent<InitializedEvent.InputTuple, InitializedEvent.OutputTuple, InitializedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'Paused'): TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
getEvent(key: 'TeamBattleCancelled'): TypedContractEvent<TeamBattleCancelledEvent.InputTuple, TeamBattleCancelledEvent.OutputTuple, TeamBattleCancelledEvent.OutputObject>;
getEvent(key: 'TeamBattleCreated'): TypedContractEvent<TeamBattleCreatedEvent.InputTuple, TeamBattleCreatedEvent.OutputTuple, TeamBattleCreatedEvent.OutputObject>;
getEvent(key: 'TeamBattleJoined'): TypedContractEvent<TeamBattleJoinedEvent.InputTuple, TeamBattleJoinedEvent.OutputTuple, TeamBattleJoinedEvent.OutputObject>;
getEvent(key: 'TeamBattleResolved'): TypedContractEvent<TeamBattleResolvedEvent.InputTuple, TeamBattleResolvedEvent.OutputTuple, TeamBattleResolvedEvent.OutputObject>;
getEvent(key: 'TrustedSignerUpdated'): TypedContractEvent<TrustedSignerUpdatedEvent.InputTuple, TrustedSignerUpdatedEvent.OutputTuple, TrustedSignerUpdatedEvent.OutputObject>;
getEvent(key: 'Unpaused'): TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
getEvent(key: 'Upgraded'): TypedContractEvent<UpgradedEvent.InputTuple, UpgradedEvent.OutputTuple, UpgradedEvent.OutputObject>;

    filters: {
      
      'AdminAdded(address)': TypedContractEvent<AdminAddedEvent.InputTuple, AdminAddedEvent.OutputTuple, AdminAddedEvent.OutputObject>;
      AdminAdded: TypedContractEvent<AdminAddedEvent.InputTuple, AdminAddedEvent.OutputTuple, AdminAddedEvent.OutputObject>;
    

      'AdminRemoved(address)': TypedContractEvent<AdminRemovedEvent.InputTuple, AdminRemovedEvent.OutputTuple, AdminRemovedEvent.OutputObject>;
      AdminRemoved: TypedContractEvent<AdminRemovedEvent.InputTuple, AdminRemovedEvent.OutputTuple, AdminRemovedEvent.OutputObject>;
    

      'ContractPaused(address)': TypedContractEvent<ContractPausedEvent.InputTuple, ContractPausedEvent.OutputTuple, ContractPausedEvent.OutputObject>;
      ContractPaused: TypedContractEvent<ContractPausedEvent.InputTuple, ContractPausedEvent.OutputTuple, ContractPausedEvent.OutputObject>;
    

      'ContractUnpaused(address)': TypedContractEvent<ContractUnpausedEvent.InputTuple, ContractUnpausedEvent.OutputTuple, ContractUnpausedEvent.OutputObject>;
      ContractUnpaused: TypedContractEvent<ContractUnpausedEvent.InputTuple, ContractUnpausedEvent.OutputTuple, ContractUnpausedEvent.OutputObject>;
    

      'Initialized(uint64)': TypedContractEvent<InitializedEvent.InputTuple, InitializedEvent.OutputTuple, InitializedEvent.OutputObject>;
      Initialized: TypedContractEvent<InitializedEvent.InputTuple, InitializedEvent.OutputTuple, InitializedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'Paused(address)': TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
      Paused: TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
    

      'TeamBattleCancelled(uint256,address)': TypedContractEvent<TeamBattleCancelledEvent.InputTuple, TeamBattleCancelledEvent.OutputTuple, TeamBattleCancelledEvent.OutputObject>;
      TeamBattleCancelled: TypedContractEvent<TeamBattleCancelledEvent.InputTuple, TeamBattleCancelledEvent.OutputTuple, TeamBattleCancelledEvent.OutputObject>;
    

      'TeamBattleCreated(uint256,address,uint256[3],uint256)': TypedContractEvent<TeamBattleCreatedEvent.InputTuple, TeamBattleCreatedEvent.OutputTuple, TeamBattleCreatedEvent.OutputObject>;
      TeamBattleCreated: TypedContractEvent<TeamBattleCreatedEvent.InputTuple, TeamBattleCreatedEvent.OutputTuple, TeamBattleCreatedEvent.OutputObject>;
    

      'TeamBattleJoined(uint256,address,uint256[3])': TypedContractEvent<TeamBattleJoinedEvent.InputTuple, TeamBattleJoinedEvent.OutputTuple, TeamBattleJoinedEvent.OutputObject>;
      TeamBattleJoined: TypedContractEvent<TeamBattleJoinedEvent.InputTuple, TeamBattleJoinedEvent.OutputTuple, TeamBattleJoinedEvent.OutputObject>;
    

      'TeamBattleResolved(uint256,address,address,uint8,uint8,uint256)': TypedContractEvent<TeamBattleResolvedEvent.InputTuple, TeamBattleResolvedEvent.OutputTuple, TeamBattleResolvedEvent.OutputObject>;
      TeamBattleResolved: TypedContractEvent<TeamBattleResolvedEvent.InputTuple, TeamBattleResolvedEvent.OutputTuple, TeamBattleResolvedEvent.OutputObject>;
    

      'TrustedSignerUpdated(address)': TypedContractEvent<TrustedSignerUpdatedEvent.InputTuple, TrustedSignerUpdatedEvent.OutputTuple, TrustedSignerUpdatedEvent.OutputObject>;
      TrustedSignerUpdated: TypedContractEvent<TrustedSignerUpdatedEvent.InputTuple, TrustedSignerUpdatedEvent.OutputTuple, TrustedSignerUpdatedEvent.OutputObject>;
    

      'Unpaused(address)': TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
      Unpaused: TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
    

      'Upgraded(address)': TypedContractEvent<UpgradedEvent.InputTuple, UpgradedEvent.OutputTuple, UpgradedEvent.OutputObject>;
      Upgraded: TypedContractEvent<UpgradedEvent.InputTuple, UpgradedEvent.OutputTuple, UpgradedEvent.OutputObject>;
    
    };
  }